export const ERR_UNKNOWN_RECORD_TYPE = 'ERR_UNKNOWN_RECORD_TYPE';
export const ERR_UNKNOWN_VOCABULARY = 'ERR_UNKNOWN_VOCABULARY';
export const ERR_MISSING_VOCABULARY = 'ERR_MISSING_VOCABULARY';
export const ERR_UNKNOWN_SUBRESOURCE = 'ERR_UNKNOWN_SUBRESOURCE';
export const ERR_INVALID_CSID = 'ERR_INVALID_CSID';
export const ERR_INVALID_RELATED_TYPE = 'ERR_INVALID_RELATED_TYPE';
export const ERR_INVALID_SORT = 'ERR_INVALID_SORT';
export const ERR_API = 'ERR_API';

export const ERR_MISSING_REQ_FIELD = 'ERR_MISSING_REQ_FIELD';
export const ERR_DATA_TYPE = 'ERR_DATA_TYPE';
