name: Continuous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    name: Check code
    uses: collectionspace/.github/.github/workflows/check-js.yml@main

  upload-coverage:
    name: Upload coverage report
    needs: check
    runs-on: macos-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      
      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/lcov.info
