name: Continuous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    name: Check code
    uses: collectionspace/.github/.github/workflows/check-js.yml@main
